#!/bin/bash

declare -A COLORS=(
  ["crit"]="#e35454"
  ["good"]="#529f45"
  ["warn"]="#e3bf55"
)

declare -A ICONS=(
  ["/"]="/"
  ["/home"]="" # FA Home icon

  ["keyboard"]=""
  ["mem"]=""
  ["onoff"]=""
  ["eye"]=""
  ["bluetooth"]=""

  ["net_down"]=""
  ["net_off"]=""
  ["net_rx"]=""
  ["net_tx"]=""

  ["umbrella"]=""
  ["sun"]=""
  ["moon"]=""

  ["music"]=" "
  ["play"]=""
  ["pause"]=""
  ["stop"]=""
  ["headphones"]=""
)

_color() {
  echo ${COLORS[$1]}
}

_human() {
  numfmt --to iec $1
}

_icon() {
  [[ ! -z ${ICONS[$1]} ]] \
    && <<< ${ICONS[$1]} \
    || ([[ ! -z $2 ]] \
      && <<< $2 \
      || <<< "?")
}

_span() {
  local content=$1
  local color=$2
  local cattr=$([ ! -z "$color" ] && <<< "color=\"$color\"")

  echo "<span $cattr>$content</span>"
}
